# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # Using 18.x and 20.x as they are LTS versions and most stable for production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build the project
      run: npm run build
      
    - name: Check build output
      run: |
        if [ -d "build" ]; then
          echo "Build successful - build directory exists"
          ls -la build/
        else
          echo "Build failed - build directory not found"
          exit 1
        fi
